[2023-12-20 23:44:09,534] 96 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.29.68:5000
[2023-12-20 23:44:09,534] 96 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2023-12-20 23:45:01,266] 96 - werkzeug - INFO - 127.0.0.1 - - [20/Dec/2023 23:45:01] "GET / HTTP/1.1" 200 -
[2023-12-20 23:45:01,324] 96 - werkzeug - INFO - 127.0.0.1 - - [20/Dec/2023 23:45:01] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2023-12-20 23:45:03,616] 96 - werkzeug - INFO - 127.0.0.1 - - [20/Dec/2023 23:45:03] "GET / HTTP/1.1" 200 -
[2023-12-20 23:45:25,212] 96 - werkzeug - INFO - 127.0.0.1 - - [20/Dec/2023 23:45:25] "[33mGET /predict_datapoint HTTP/1.1[0m" 404 -
[2023-12-20 23:46:10,550] 96 - werkzeug - INFO - 127.0.0.1 - - [20/Dec/2023 23:46:10] "[33mGET /predictdata HTTP/1.1[0m" 404 -
[2023-12-20 23:46:13,757] 96 - werkzeug - INFO - 127.0.0.1 - - [20/Dec/2023 23:46:13] "[33mGET /predictdata HTTP/1.1[0m" 404 -
[2023-12-20 23:46:28,174] 96 - werkzeug - INFO - 127.0.0.1 - - [20/Dec/2023 23:46:28] "GET /predict HTTP/1.1" 200 -
[2023-12-20 23:46:55,398] 825 - app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "app.py", line 28, in predict_datapoint
    writing_score=float(request.form.get('reading_score'))
TypeError: float() argument must be a string or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Git-1\mlproject\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Git-1\mlproject\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Git-1\mlproject\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Git-1\mlproject\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 40, in predict_datapoint
    raise CustomException(e,sys)
src.exception.CustomException: Error occurred in python script name [app.py] line number [28] error message [float() argument must be a string or a number, not 'NoneType']
[2023-12-20 23:46:55,401] 96 - werkzeug - INFO - 127.0.0.1 - - [20/Dec/2023 23:46:55] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
